#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EasyPregunto")]
	public partial class DataeEasyDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertEstado_Sesion(Estado_Sesion instance);
    partial void UpdateEstado_Sesion(Estado_Sesion instance);
    partial void DeleteEstado_Sesion(Estado_Sesion instance);
    partial void InsertArea_Conocimiento(Area_Conocimiento instance);
    partial void UpdateArea_Conocimiento(Area_Conocimiento instance);
    partial void DeleteArea_Conocimiento(Area_Conocimiento instance);
    partial void InsertTipo_Documento(Tipo_Documento instance);
    partial void UpdateTipo_Documento(Tipo_Documento instance);
    partial void DeleteTipo_Documento(Tipo_Documento instance);
    partial void InsertSub_area(Sub_area instance);
    partial void UpdateSub_area(Sub_area instance);
    partial void DeleteSub_area(Sub_area instance);
    #endregion
		
		public DataeEasyDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["EasyPreguntoConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataeEasyDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataeEasyDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataeEasyDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataeEasyDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Usuario> Usuario
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Estado_Sesion> Estado_Sesion
		{
			get
			{
				return this.GetTable<Estado_Sesion>();
			}
		}
		
		public System.Data.Linq.Table<Area_Conocimiento> Area_Conocimiento
		{
			get
			{
				return this.GetTable<Area_Conocimiento>();
			}
		}
		
		public System.Data.Linq.Table<Tipo_Documento> Tipo_Documento
		{
			get
			{
				return this.GetTable<Tipo_Documento>();
			}
		}
		
		public System.Data.Linq.Table<Sub_area> Sub_area
		{
			get
			{
				return this.GetTable<Sub_area>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SubArea")]
		public ISingleResult<SubAreaResult> SubArea([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_Area", DbType="Int")] System.Nullable<int> id_Area)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Area);
			return ((ISingleResult<SubAreaResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Usuario;
		
		private string _Nombre_Usuario;
		
		private string _Apellidos_Usuario;
		
		private string _Correo_Electronico_Usuario;
		
		private string _Clave_Usuario;
		
		private string _Alias_Usuario;
		
		private int _Rol;
		
		private EntitySet<Estado_Sesion> _Estado_Sesion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_UsuarioChanging(int value);
    partial void OnId_UsuarioChanged();
    partial void OnNombre_UsuarioChanging(string value);
    partial void OnNombre_UsuarioChanged();
    partial void OnApellidos_UsuarioChanging(string value);
    partial void OnApellidos_UsuarioChanged();
    partial void OnCorreo_Electronico_UsuarioChanging(string value);
    partial void OnCorreo_Electronico_UsuarioChanged();
    partial void OnClave_UsuarioChanging(string value);
    partial void OnClave_UsuarioChanged();
    partial void OnAlias_UsuarioChanging(string value);
    partial void OnAlias_UsuarioChanged();
    partial void OnRolChanging(int value);
    partial void OnRolChanged();
    #endregion
		
		public Usuario()
		{
			this._Estado_Sesion = new EntitySet<Estado_Sesion>(new Action<Estado_Sesion>(this.attach_Estado_Sesion), new Action<Estado_Sesion>(this.detach_Estado_Sesion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Usuario
		{
			get
			{
				return this._Id_Usuario;
			}
			set
			{
				if ((this._Id_Usuario != value))
				{
					this.OnId_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Id_Usuario = value;
					this.SendPropertyChanged("Id_Usuario");
					this.OnId_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Usuario", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Nombre_Usuario
		{
			get
			{
				return this._Nombre_Usuario;
			}
			set
			{
				if ((this._Nombre_Usuario != value))
				{
					this.OnNombre_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Usuario = value;
					this.SendPropertyChanged("Nombre_Usuario");
					this.OnNombre_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos_Usuario", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Apellidos_Usuario
		{
			get
			{
				return this._Apellidos_Usuario;
			}
			set
			{
				if ((this._Apellidos_Usuario != value))
				{
					this.OnApellidos_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Apellidos_Usuario = value;
					this.SendPropertyChanged("Apellidos_Usuario");
					this.OnApellidos_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo_Electronico_Usuario", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Correo_Electronico_Usuario
		{
			get
			{
				return this._Correo_Electronico_Usuario;
			}
			set
			{
				if ((this._Correo_Electronico_Usuario != value))
				{
					this.OnCorreo_Electronico_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Correo_Electronico_Usuario = value;
					this.SendPropertyChanged("Correo_Electronico_Usuario");
					this.OnCorreo_Electronico_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clave_Usuario", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Clave_Usuario
		{
			get
			{
				return this._Clave_Usuario;
			}
			set
			{
				if ((this._Clave_Usuario != value))
				{
					this.OnClave_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Clave_Usuario = value;
					this.SendPropertyChanged("Clave_Usuario");
					this.OnClave_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alias_Usuario", DbType="VarChar(30)")]
		public string Alias_Usuario
		{
			get
			{
				return this._Alias_Usuario;
			}
			set
			{
				if ((this._Alias_Usuario != value))
				{
					this.OnAlias_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Alias_Usuario = value;
					this.SendPropertyChanged("Alias_Usuario");
					this.OnAlias_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol", DbType="Int NOT NULL")]
		public int Rol
		{
			get
			{
				return this._Rol;
			}
			set
			{
				if ((this._Rol != value))
				{
					this.OnRolChanging(value);
					this.SendPropertyChanging();
					this._Rol = value;
					this.SendPropertyChanged("Rol");
					this.OnRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Estado_Sesion", Storage="_Estado_Sesion", ThisKey="Id_Usuario", OtherKey="Usuario")]
		public EntitySet<Estado_Sesion> Estado_Sesion
		{
			get
			{
				return this._Estado_Sesion;
			}
			set
			{
				this._Estado_Sesion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Estado_Sesion(Estado_Sesion entity)
		{
			this.SendPropertyChanging();
			entity.Usuario1 = this;
		}
		
		private void detach_Estado_Sesion(Estado_Sesion entity)
		{
			this.SendPropertyChanging();
			entity.Usuario1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Estado_Sesion")]
	public partial class Estado_Sesion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Estado_Sesion;
		
		private string _Estado;
		
		private int _Usuario;
		
		private int _Tutor;
		
		private int _idarea;
		
		private EntityRef<Usuario> _Usuario1;
		
		private EntityRef<Area_Conocimiento> _Area_Conocimiento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_Estado_SesionChanging(int value);
    partial void OnId_Estado_SesionChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnUsuarioChanging(int value);
    partial void OnUsuarioChanged();
    partial void OnTutorChanging(int value);
    partial void OnTutorChanged();
    partial void OnidareaChanging(int value);
    partial void OnidareaChanged();
    #endregion
		
		public Estado_Sesion()
		{
			this._Usuario1 = default(EntityRef<Usuario>);
			this._Area_Conocimiento = default(EntityRef<Area_Conocimiento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Estado_Sesion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Estado_Sesion
		{
			get
			{
				return this._Id_Estado_Sesion;
			}
			set
			{
				if ((this._Id_Estado_Sesion != value))
				{
					this.OnId_Estado_SesionChanging(value);
					this.SendPropertyChanging();
					this._Id_Estado_Sesion = value;
					this.SendPropertyChanged("Id_Estado_Sesion");
					this.OnId_Estado_SesionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="Int NOT NULL")]
		public int Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					if (this._Usuario1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tutor", DbType="Int NOT NULL")]
		public int Tutor
		{
			get
			{
				return this._Tutor;
			}
			set
			{
				if ((this._Tutor != value))
				{
					this.OnTutorChanging(value);
					this.SendPropertyChanging();
					this._Tutor = value;
					this.SendPropertyChanged("Tutor");
					this.OnTutorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idarea")]
		public int idarea
		{
			get
			{
				return this._idarea;
			}
			set
			{
				if ((this._idarea != value))
				{
					if (this._Area_Conocimiento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidareaChanging(value);
					this.SendPropertyChanging();
					this._idarea = value;
					this.SendPropertyChanged("idarea");
					this.OnidareaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Estado_Sesion", Storage="_Usuario1", ThisKey="Usuario", OtherKey="Id_Usuario", IsForeignKey=true)]
		public Usuario Usuario1
		{
			get
			{
				return this._Usuario1.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario1.Entity;
				if (((previousValue != value) 
							|| (this._Usuario1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario1.Entity = null;
						previousValue.Estado_Sesion.Remove(this);
					}
					this._Usuario1.Entity = value;
					if ((value != null))
					{
						value.Estado_Sesion.Add(this);
						this._Usuario = value.Id_Usuario;
					}
					else
					{
						this._Usuario = default(int);
					}
					this.SendPropertyChanged("Usuario1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Area_Conocimiento_Estado_Sesion", Storage="_Area_Conocimiento", ThisKey="idarea", OtherKey="Id_Area", IsForeignKey=true)]
		public Area_Conocimiento Area_Conocimiento
		{
			get
			{
				return this._Area_Conocimiento.Entity;
			}
			set
			{
				Area_Conocimiento previousValue = this._Area_Conocimiento.Entity;
				if (((previousValue != value) 
							|| (this._Area_Conocimiento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Area_Conocimiento.Entity = null;
						previousValue.Estado_Sesion.Remove(this);
					}
					this._Area_Conocimiento.Entity = value;
					if ((value != null))
					{
						value.Estado_Sesion.Add(this);
						this._idarea = value.Id_Area;
					}
					else
					{
						this._idarea = default(int);
					}
					this.SendPropertyChanged("Area_Conocimiento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Area_Conocimiento")]
	public partial class Area_Conocimiento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Area;
		
		private string _Nombre_Area;
		
		private EntitySet<Sub_area> _Sub_area;
		
		private EntitySet<Estado_Sesion> _Estado_Sesion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_AreaChanging(int value);
    partial void OnId_AreaChanged();
    partial void OnNombre_AreaChanging(string value);
    partial void OnNombre_AreaChanged();
    #endregion
		
		public Area_Conocimiento()
		{
			this._Sub_area = new EntitySet<Sub_area>(new Action<Sub_area>(this.attach_Sub_area), new Action<Sub_area>(this.detach_Sub_area));
			this._Estado_Sesion = new EntitySet<Estado_Sesion>(new Action<Estado_Sesion>(this.attach_Estado_Sesion), new Action<Estado_Sesion>(this.detach_Estado_Sesion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Area", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Area
		{
			get
			{
				return this._Id_Area;
			}
			set
			{
				if ((this._Id_Area != value))
				{
					this.OnId_AreaChanging(value);
					this.SendPropertyChanging();
					this._Id_Area = value;
					this.SendPropertyChanged("Id_Area");
					this.OnId_AreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Area", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nombre_Area
		{
			get
			{
				return this._Nombre_Area;
			}
			set
			{
				if ((this._Nombre_Area != value))
				{
					this.OnNombre_AreaChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Area = value;
					this.SendPropertyChanged("Nombre_Area");
					this.OnNombre_AreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Area_Conocimiento_Sub_area", Storage="_Sub_area", ThisKey="Id_Area", OtherKey="Area")]
		public EntitySet<Sub_area> Sub_area
		{
			get
			{
				return this._Sub_area;
			}
			set
			{
				this._Sub_area.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Area_Conocimiento_Estado_Sesion", Storage="_Estado_Sesion", ThisKey="Id_Area", OtherKey="idarea")]
		public EntitySet<Estado_Sesion> Estado_Sesion
		{
			get
			{
				return this._Estado_Sesion;
			}
			set
			{
				this._Estado_Sesion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Sub_area(Sub_area entity)
		{
			this.SendPropertyChanging();
			entity.Area_Conocimiento = this;
		}
		
		private void detach_Sub_area(Sub_area entity)
		{
			this.SendPropertyChanging();
			entity.Area_Conocimiento = null;
		}
		
		private void attach_Estado_Sesion(Estado_Sesion entity)
		{
			this.SendPropertyChanging();
			entity.Area_Conocimiento = this;
		}
		
		private void detach_Estado_Sesion(Estado_Sesion entity)
		{
			this.SendPropertyChanging();
			entity.Area_Conocimiento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tipo_Documento")]
	public partial class Tipo_Documento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Documento;
		
		private string _Nombre_Documento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_DocumentoChanging(int value);
    partial void OnId_DocumentoChanged();
    partial void OnNombre_DocumentoChanging(string value);
    partial void OnNombre_DocumentoChanged();
    #endregion
		
		public Tipo_Documento()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Documento", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Documento
		{
			get
			{
				return this._Id_Documento;
			}
			set
			{
				if ((this._Id_Documento != value))
				{
					this.OnId_DocumentoChanging(value);
					this.SendPropertyChanging();
					this._Id_Documento = value;
					this.SendPropertyChanged("Id_Documento");
					this.OnId_DocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Documento", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nombre_Documento
		{
			get
			{
				return this._Nombre_Documento;
			}
			set
			{
				if ((this._Nombre_Documento != value))
				{
					this.OnNombre_DocumentoChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Documento = value;
					this.SendPropertyChanged("Nombre_Documento");
					this.OnNombre_DocumentoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sub_area")]
	public partial class Sub_area : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Sub_Area;
		
		private string _Nombre_Sub;
		
		private int _Area;
		
		private EntityRef<Area_Conocimiento> _Area_Conocimiento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_Sub_AreaChanging(int value);
    partial void OnId_Sub_AreaChanged();
    partial void OnNombre_SubChanging(string value);
    partial void OnNombre_SubChanged();
    partial void OnAreaChanging(int value);
    partial void OnAreaChanged();
    #endregion
		
		public Sub_area()
		{
			this._Area_Conocimiento = default(EntityRef<Area_Conocimiento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Sub_Area", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Sub_Area
		{
			get
			{
				return this._Id_Sub_Area;
			}
			set
			{
				if ((this._Id_Sub_Area != value))
				{
					this.OnId_Sub_AreaChanging(value);
					this.SendPropertyChanging();
					this._Id_Sub_Area = value;
					this.SendPropertyChanged("Id_Sub_Area");
					this.OnId_Sub_AreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Sub", DbType="VarChar(30)")]
		public string Nombre_Sub
		{
			get
			{
				return this._Nombre_Sub;
			}
			set
			{
				if ((this._Nombre_Sub != value))
				{
					this.OnNombre_SubChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Sub = value;
					this.SendPropertyChanged("Nombre_Sub");
					this.OnNombre_SubChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area", DbType="Int NOT NULL")]
		public int Area
		{
			get
			{
				return this._Area;
			}
			set
			{
				if ((this._Area != value))
				{
					if (this._Area_Conocimiento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAreaChanging(value);
					this.SendPropertyChanging();
					this._Area = value;
					this.SendPropertyChanged("Area");
					this.OnAreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Area_Conocimiento_Sub_area", Storage="_Area_Conocimiento", ThisKey="Area", OtherKey="Id_Area", IsForeignKey=true)]
		public Area_Conocimiento Area_Conocimiento
		{
			get
			{
				return this._Area_Conocimiento.Entity;
			}
			set
			{
				Area_Conocimiento previousValue = this._Area_Conocimiento.Entity;
				if (((previousValue != value) 
							|| (this._Area_Conocimiento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Area_Conocimiento.Entity = null;
						previousValue.Sub_area.Remove(this);
					}
					this._Area_Conocimiento.Entity = value;
					if ((value != null))
					{
						value.Sub_area.Add(this);
						this._Area = value.Id_Area;
					}
					else
					{
						this._Area = default(int);
					}
					this.SendPropertyChanged("Area_Conocimiento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class SubAreaResult
	{
		
		private string _Nombre_Sub;
		
		public SubAreaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Sub", DbType="VarChar(30)")]
		public string Nombre_Sub
		{
			get
			{
				return this._Nombre_Sub;
			}
			set
			{
				if ((this._Nombre_Sub != value))
				{
					this._Nombre_Sub = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
